Web/Areas/Admin/Models/FinancialItems/CreateFinancialItemViewModel.cs
using Core.Resources;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.Enums;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.Areas.Admin.Models.FinancialItems
{
    public class CreateFinancialItemViewModel
    {
        public int UserId { get; set; }

        public string UserName { get; set; }

        [Required(ErrorMessageResourceName = nameof(Literals.RequiredFieldError), ErrorMessageResourceType = typeof(Literals))]
        [MaxLength(50, ErrorMessageResourceType = typeof(Literals), ErrorMessageResourceName = nameof(Literals.MaxLengthError))]
        public string Name { get; set; }

        [Required(ErrorMessageResourceName = nameof(Literals.RequiredFieldError), ErrorMessageResourceType = typeof(Literals))]
        public FinancialItemType Type { get; set; }

        public IEnumerable<SelectListItem> Types { get; set; }
    }
}

Web/Areas/Admin/Models/FinancialItems/EditFinancialItemViewModel.cs
using Core.Resources;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.Enums;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.Areas.Admin.Models.FinancialItems
{
    public class EditFinancialItemViewModel
    {
        public int Id { get; set; }

        public int UserId { get; set; }

        public string UserName { get; set; }

        [Required(ErrorMessageResourceName = nameof(Literals.RequiredFieldError), ErrorMessageResourceType = typeof(Literals))]
        [MaxLength(50, ErrorMessageResourceType = typeof(Literals), ErrorMessageResourceName = nameof(Literals.MaxLengthError))]
        public string Name { get; set; }

        [Required(ErrorMessageResourceName = nameof(Literals.RequiredFieldError), ErrorMessageResourceType = typeof(Literals))]
        public FinancialItemType Type { get; set; }

        public bool IsActive { get; set; }

        public IEnumerable<SelectListItem> Types { get; set; }
    }
}

Web/Areas/Admin/Models/FinancialItems/FinancialItemListViewModel.cs
using Models;
using Models.Entities;

namespace Web.Areas.Admin.Models.FinancialItems
{
    public class FinancialItemListViewModel
    {
        public int UserId { get; set; }

        public string UserName { get; set; }

        public PagedList<FinancialItem> FinancialItems { get; set; }
    }
}

Web/Models/FinancialItems/CreateFinancialItemViewModel.cs
using Core.Resources;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.Enums;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.Models.FinancialItems
{
    public class CreateFinancialItemViewModel
    {
        [Required(ErrorMessageResourceName = nameof(Literals.RequiredFieldError), ErrorMessageResourceType = typeof(Literals))]
        [MaxLength(50, ErrorMessageResourceType = typeof(Literals), ErrorMessageResourceName = nameof(Literals.MaxLengthError))]
        public string Name { get; set; }

        [Required(ErrorMessageResourceName = nameof(Literals.RequiredFieldError), ErrorMessageResourceType = typeof(Literals))]
        public FinancialItemType Type { get; set; }

        public IEnumerable<SelectListItem> Types { get; set; }
    }
}

Web/Models/FinancialItems/EditFinancialItemViewModel.cs
using Core.Resources;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.Enums;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.Models.FinancialItems
{
    public class EditFinancialItemViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessageResourceName = nameof(Literals.RequiredFieldError), ErrorMessageResourceType = typeof(Literals))]
        [MaxLength(50, ErrorMessageResourceType = typeof(Literals), ErrorMessageResourceName = nameof(Literals.MaxLengthError))]
        public string Name { get; set; }

        [Required(ErrorMessageResourceName = nameof(Literals.RequiredFieldError), ErrorMessageResourceType = typeof(Literals))]
        public FinancialItemType Type { get; set; }

        public bool IsActive { get; set; }

        public IEnumerable<SelectListItem> Types { get; set; }
    }
}

Web/Models/FinancialItems/FinancialItemListViewModel.cs
using Models;
using Models.Entities;

namespace Web.Models.FinancialItems
{
    public class FinancialItemListViewModel
    {
        public PagedList<FinancialItem> FinancialItems { get; set; }
    }
}

Web/Areas/Admin/Controllers/FinancialItemsController.cs
using Core.Constants;
using Core.Contracts.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.DatatableModels;
using Models.Entities;
using Models.Enums;
using System;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Admin.Models.FinancialItems;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class FinancialItemsController : Controller
    {
        private readonly IFinancialItemsService _financialItemsService;
        private readonly IUserService _userService;

        public FinancialItemsController(IFinancialItemsService financialItemsService, IUserService userService)
        {
            _financialItemsService = financialItemsService;
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Index([FromRoute]int id)
        {
            var model = new FinancialItemListViewModel()
            {
                UserId = id
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create(int userId)
        {
            var user = await _userService.GetByIdAsync(userId);

            if (user == null)
            {
                return NotFound(user);
            }

            var model = new CreateFinancialItemViewModel();
            model.UserId = userId;
            model.UserName = user.UserName;
            model.Types = new SelectList(Enum.GetNames(typeof(FinancialItemType)));

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateFinancialItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                var financialItem = new FinancialItem()
                {

                    Name = model.Name,
                    Type = model.Type,
                    UserId = model.UserId,
                    IsActive = true
                };

                await _financialItemsService.CreateAsync(financialItem);

                return RedirectToAction(nameof(FinancialItemsController.Index), new { id = financialItem.UserId });
            }

            model.Types = new SelectList(Enum.GetNames(typeof(FinancialItemType)));

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var financialItem = await _financialItemsService.GetByIdAsync(id);

            if (financialItem == null)
            {
                return NotFound(financialItem);
            }

            var user = await _userService.GetByIdAsync(financialItem.UserId);

            if (user == null)
            {
                return NotFound(user);
            }

            var model = new EditFinancialItemViewModel()
            {
                Id = financialItem.Id,
                UserId = financialItem.UserId,
                UserName = user.UserName,
                Name = financialItem.Name,
                Type = financialItem.Type,
                IsActive = financialItem.IsActive,
                Types = new SelectList(Enum.GetNames(typeof(FinancialItemType)))
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditFinancialItemViewModel model)
        {
            var financialItem = await _financialItemsService.GetByIdAsync(model.Id);

            if (financialItem == null)
            {
                return NotFound(financialItem);
            }

            if (ModelState.IsValid)
            {
                financialItem.Name = model.Name;
                financialItem.Type = model.Type;
                financialItem.IsActive = model.IsActive;

                await _financialItemsService.UpdateAsync(financialItem);

                return RedirectToAction(nameof(FinancialItemsController.Index), new { id = financialItem.UserId });
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var financialItem = await _financialItemsService.GetByIdAsync(id);

            if (financialItem == null)
            {
                return NotFound(financialItem);
            }

            await _financialItemsService.DeleteAsync(id);

            return RedirectToAction(nameof(FinancialItemsController.Index), new { id = financialItem.UserId });
        }

        #region Ajax Methods

        [HttpPost]
        public async Task<IActionResult> LoadItemsTable([FromBody]DTParameters dtParameters)
        {
            var userIdString = dtParameters.AdditionalValues.FirstOrDefault();

            if (string.IsNullOrWhiteSpace(userIdString) || !int.TryParse(userIdString, out int userId))
            {
                return NotFound(userIdString);
            }

            var result = await _financialItemsService.GetFilteredItemsByUserIdAsync(userId, dtParameters);

            // now just get the count of items (without the skip and take) - eg how many could be returned with filtering
            var filteredResultsCount = result.Count();
            var totalResultsCount = await _financialItemsService.GetCountByUserIdAsync(userId);

            return Json(new
            {
                draw = dtParameters.Draw,
                recordsTotal = totalResultsCount,
                recordsFiltered = filteredResultsCount,
                data = result
                    .Skip(dtParameters.Start)
                    .Take(dtParameters.Length)
                    .ToList()
            });
        }

        #endregion
    }
}

Web/Controllers/FinancialItemsController.cs
using Core.Constants;
using Core.Contracts.Services;
using Core.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;
using Models.DatatableModels;
using Models.Entities;
using Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Models.FinancialItems;

namespace Web.Controllers
{
    [Authorize(Roles = Roles.User)]
    public class FinancialItemsController : Controller
    {
        private readonly IFinancialItemsService _financialItemsService;

        public FinancialItemsController(IFinancialItemsService financialItemsService)
        {
            _financialItemsService = financialItemsService;
        }

        public async Task<IActionResult> Index(PagedListRequest request)
        {
            var userId = User.GetCurrentUserId();
            var financialItems = await _financialItemsService.GetPagedByUserIdAsync(userId, request);

            var model = new FinancialItemListViewModel()
            {
                FinancialItems = financialItems
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new CreateFinancialItemViewModel();
            model.Types = new SelectList(Enum.GetNames(typeof(FinancialItemType)));

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateFinancialItemViewModel model)
        {
            var userId = User.GetCurrentUserId();

            if (ModelState.IsValid)
            {
                var financialItem = new FinancialItem()
                {
                    Name = model.Name,
                    Type = model.Type,
                    UserId = userId,
                    IsActive = true
                };

                await _financialItemsService.CreateAsync(financialItem);

                return RedirectToAction(nameof(FinancialItemsController.Index));
            }

            model.Types = new SelectList(Enum.GetNames(typeof(FinancialItemType)));

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var userId = User.GetCurrentUserId();
            var financialItem = await _financialItemsService.GetByIdAndUserIdAsync(id, userId);

            if (financialItem == null)
            {
                return NotFound(financialItem);
            }

            var model = new EditFinancialItemViewModel()
            {
                Id = financialItem.Id,
                Name = financialItem.Name,
                Type = financialItem.Type,
                IsActive = financialItem.IsActive,
                Types = new SelectList(Enum.GetNames(typeof(FinancialItemType)))
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditFinancialItemViewModel model)
        {
            var userId = User.GetCurrentUserId();
            var financialItem = await _financialItemsService.GetByIdAndUserIdAsync(model.Id, userId);

            if (financialItem == null)
            {
                return NotFound(financialItem);
            }

            if (ModelState.IsValid)
            {
                financialItem.Name = model.Name;
                financialItem.Type = model.Type;
                financialItem.IsActive = model.IsActive;

                await _financialItemsService.UpdateAsync(financialItem);

                return RedirectToAction(nameof(FinancialItemsController.Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var userId = User.GetCurrentUserId();
            await _financialItemsService.DeleteAsync(id, userId);

            return RedirectToAction(nameof(Index));
        }

        #region Ajax Methods

        [HttpGet]
        public async Task<JsonResult> GetSimplifiedItems(FinancialItemType type)
        {
            var id = HttpContext.User.GetCurrentUserId();
            IEnumerable<FinancialItem> items = null;

            if (type == FinancialItemType.Income)
            {
                items = await _financialItemsService.GetIncomeByUserIdAsync(id);
            }
            else
            {
                items = await _financialItemsService.GetExpensesByUserIdAsync(id);
            }

            var itemsSimplified = items.Select(fi => new { id = fi.Id, name = fi.Name });

            return Json(itemsSimplified);
        }

        #endregion

        #region Ajax Methods

        [HttpPost]
        public async Task<IActionResult> LoadTable([FromBody]DTParameters dtParameters)
        {
            var userId = User.GetCurrentUserId();


            var result = await _financialItemsService.GetFilteredItemsByUserIdAsync(userId, dtParameters);

            // now just get the count of items (without the skip and take) - eg how many could be returned with filtering
            var filteredResultsCount = result.Count();
            var totalResultsCount = await _financialItemsService.GetCountByUserIdAsync(userId);

            return Json(new
            {
                draw = dtParameters.Draw,
                recordsTotal = totalResultsCount,
                recordsFiltered = filteredResultsCount,
                data = result
                    .Skip(dtParameters.Start)
                    .Take(dtParameters.Length)
                    .ToList()
            });
        }

        #endregion
    }
}

Web/ViewComponents/DeleteConfirmationDialogViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Web.Models.Common;

namespace Web.ViewComponents
{
    /// <summary>
    /// A view component that represents the delete confirmation dialog.
    /// </summary>
    /// <seealso cref="ViewComponent" />
    public class DeleteConfirmationDialogViewComponent : ViewComponent
    {
        /// <summary>
        /// Invokes the view component.
        /// </summary>
        /// <param name="dialogId">The dialog identifier.</param>
        /// <param name="title">The title.</param>
        /// <param name="text">The text.</param>
        /// <param name="url">The URL.</param>
        public IViewComponentResult Invoke(string dialogId, string title, string text, string url)
        {
            return View(new DeleteConfirmationDialogViewModel()
            {
                Id = dialogId,
                Title = title,
                Text = text,
                Url = url
            });
        }
    }
}

Web/Views/FinancialItems/Create.cshtml
@model Web.Models.FinancialItems.CreateFinancialItemViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-6 offset-3">
        <div class="text-center">
            <h1>@ViewData["Title"]</h1>
        </div>

        <form method="post" asp-action="@nameof(FinancialItemsController.Create)">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <label asp-for="Name">Name</label>

            <div class="form-group">
                <input asp-for="Name" placeholder="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <label asp-for="Type">Type</label>
            <div class="form-group">
                <select asp-for="Type" asp-items="@Model.Types" placeholder="Type" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>

            <div class="input-group">
                <button type="submit" class="btn btn-primary form-control mr-1">Save</button>
                <a class="btn btn-outline-secondary form-control ml-1" asp-action="@nameof(FinancialItemsController.Index)">Cancel</a>
            </div>
        </form>
    </div>
</div>

Web/Views/FinancialItems/Edit.cshtml
@model Web.Models.FinancialItems.EditFinancialItemViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-6 offset-3">
        <div class="text-center">
            <h1>@ViewData["Title"]</h1>
        </div>

        <div class="d-flex justify-content-start mb-2">
            <a class="btn btn-primary btn-sm" asp-controller="@Url.ControllerName(typeof(FinancialOperationsController))" asp-action="@nameof(FinancialOperationsController.Index)">
                <span class="fas fa-arrow-alt-circle-left"></span>
                Back
            </a>
        </div>

        <form method="post" asp-action="@nameof(FinancialItemsController.Edit)">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <label asp-for="Name">Name</label>

            <div class="form-group">
                <input asp-for="Name" placeholder="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <label asp-for="Type">Type</label>
            <div class="form-group">
                <select asp-for="Type" asp-items="@Model.Types" placeholder="Type" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>

            <div class="form-check">
                <input asp-for="IsActive" class="form-check-input">
                <label asp-for="IsActive">Active</label>
            </div>

            <div class="input-group">
                <button type="submit" class="btn btn-primary form-control mr-1">Save</button>
                <a class="btn btn-outline-secondary form-control ml-1" asp-action="@nameof(FinancialItemsController.Index)">Cancel</a>
            </div>

            <button type="button"
                    class="btn btn-outline-danger btn-block mt-2"
                    data-toggle="modal"
                    data-target="#delete-item-confirmation">
                Delete Item
            </button>
        </form>
    </div>
</div>

<vc:delete-confirmation-dialog dialog-id="delete-item-confirmation"
                               title="Delete Item"
                               text="Are you sure you want to delete the selected item? This will delete all operations associated with this item."
                               url="@Url.Action(nameof(FinancialOperationsController.Delete), new { id = Model.Id })" />

Web/Views/FinancialItems/Index.cshtml
@model Web.Models.FinancialItems.FinancialItemListViewModel

@{
    ViewData["Title"] = "Financial items";
}

<div class="row">
    <div class="col-12 overflow-auto">
        <h1 class="text-center">
            @ViewData["Title"]
        </h1>

        <div class="d-flex justify-content-start col-md-8 offset-md-2 mb-2">
            <a class="btn btn-primary btn-sm" asp-controller="@Url.ControllerName(typeof(FinancialOperationsController))" asp-action="@nameof(FinancialOperationsController.Index)">
                <span class="fas fa-arrow-alt-circle-left"></span>
                Back
            </a>
        </div>

        <div class="d-flex justify-content-end col-md-8 offset-md-2 mb-2">
            <a class="btn btn-primary btn-sm"
               asp-action="@nameof(FinancialItemsController.Create)">
                <span class="fas fa-plus"></span>
                Add
            </a>
        </div>

        <div class="table-responsive col-md-8 offset-md-2">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <table class="table table-hover table-bordered dataTable" id="dataTable" width="100%">
                    <thead class="table-header">
                        <tr>
                            <th tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" aria-sort="descending">
                                Name
                            </th>
                            <th tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" aria-sort="descending">
                                Type
                            </th>
                            <th tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" aria-sort="descending">
                                Active
                            </th>
                            <th class="no-sort" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" aria-sort="descending">
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $("#dataTable").DataTable({
                // Design Assets
                stateSave: true,
                autoWidth: true,
                // ServerSide Setups
                processing: true,
                serverSide: true,
                // Paging Setups
                paging: true,
                // Searching Setups
                searching: { regex: true },
                // Ajax Filter
                ajax: {
                    url: "/FinancialItems/LoadTable",
                    type: "POST",
                    contentType: "application/json",
                    dataType: "json",
                    data: function (d) {
                        return JSON.stringify(d);
                    }
                },
                // Columns Setups
                columns: [
                    { data: "name" },
                    {
                        data: "type",
                        render: function (data, type, row) {
                            return data === 0 ? "Expense" : "Income";
                        }
                    },
                    {
                        data: "isActive",
                        render: function (data, type, row) {
                            return data === true ? "Yes" : "No";
                        }
                    },
                    {
                        data: "id",
                        render: function (data, type, row) {
                            return '<div class="text-center"><a class="btn btn-outline-primary btn-sm" href=/FinancialItems/Edit/' + data + '>Edit</a></div>'; //Hack: Partially hardcoded link
                        }
                    }
                ],
                // Column Definitions
                columnDefs: [
                    { targets: "no-sort", orderable: false },
                    { targets: "no-search", searchable: false },
                    {
                        targets: "trim",
                        render: function (data, type, full, meta) {
                            if (type === "display") {
                                data = strtrunc(data, 10);
                            }

                            return data;
                        }
                    },
                    { targets: "date-type", type: "date-eu" }
                ]
            });
        });
    </script>
}